name: Self-hosted [OFRP] Local Builder

on:
  workflow_dispatch:
    inputs:
      MANIFEST_PATH:
        description: 'OrangeFox Manifest Path'
        required: true
        default: '/home/runner/_work/OrangeFox'
      MANIFEST_BRANCH:
        description: 'OrangeFox Manifest Path'
        required: true
        default: 'fox_9.0'
      DEVICE_NAME:
        description: 'Specify your Device Codename' # As is, just like your PRODUCT_DEVICE in your device tree.
        required: true
        default: 'sl8541e_cus_go'
      MAKEFILE_NAME:
        description: 'MAKEFILE_NAME'
        required: true
        default: 'omni_sl8541e_cus_go.mk'
      DEVICE_PATH:
        description: 'Specify your Device Path (Check the DEVICE_PATH in BoardConfig.mk)' # As is, just like your DEVICE_PATH in your BoardConfig.mk
        required: true
        default: 'device/sprd/sl8541e_cus_go'
      BUILD_TARGET:
        description: 'Specify your Build Target'
        required: true
        default: 'recovery'
      CLEANUP:
        description: 'Enable Cleanup action (disable to speed up building)'
        required: true
        type: boolean
        default: true
        
jobs:
  build:
    name: Build OFRP by ${{ github.actor }}
    runs-on: self-hosted
    container:
       image: ubuntu:ofrpact-20.04
#    if: github.event.repository.owner.id == github.event.sender.id
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Display Inputs
      run: |
        echo "Displaying variables/inputs."
        echo "Manifest PATH: ${{ inputs.MANIFEST_PATH }}"
        echo "Manifest Branch: ${{ inputs.MANIFEST_BRANCH }}"
        echo "Device Name: ${{ inputs.DEVICE_NAME }}"
        echo "Makefile Name: ${{ inputs.MAKEFILE_NAME }}"
        echo "Device Path: ${{ inputs.DEVICE_PATH }}"
        echo "Build Target: ${{ inputs.BUILD_TARGET }}"
        if [ ${{ inputs.CLEANUP }} == true ]; then echo "Cleanup: Enabled"; else echo "Cleanup: Disabled"; fi
             
    - name: Clean-up
      uses: rokibhasansagar/slimhub_actions@main

    - name: Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 16
      
    - name: Build Environment
      run: |
        git clone https://gitlab.com/OrangeFox/misc/scripts
        cd scripts
        sudo bash setup/android_build_env.sh
      
    - name: Set-up Manifest
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/OrangeFox
        cd ${GITHUB_WORKSPACE}/OrangeFox
        cp -r ${{ inputs.MANIFEST_PATH }}"/"${{ inputs.MANIFEST_BRANCH }} ${GITHUB_WORKSPACE}/OrangeFox/
        cp -r ${{ inputs.MANIFEST_PATH }}"/sync" ${GITHUB_WORKSPACE}/OrangeFox/
        if [ ${{ inputs.MANIFEST_BRANCH }} == '11.0' ] || [ ${{ inputs.MANIFEST_BRANCH }} == '12.1' ]; then
            echo "Sync fox_${{ inputs.MANIFEST_BRANCH }} branch"
            echo "CHECK_LEGACY_BRANCH=false" >> $GITHUB_ENV
            cd sync
        else
            echo "Sync legacy fox_${{ inputs.MANIFEST_BRANCH }} branch"
            echo "CHECK_LEGACY_BRANCH=true" >> $GITHUB_ENV
            cd sync/legacy
        fi
      continue-on-error: true

    - name: Installing python2 for legacy builds
      if: env.CHECK_LEGACY_BRANCH == 'true'
      run: |
        sudo apt-get install python2 python-is-python2

    - name: Building OrangeFox
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
        set +e
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        set -e
        if [ ${{ inputs.MANIFEST_BRANCH }} == '11.0' ] || [ ${{ inputs.MANIFEST_BRANCH }} == '12.1' ]; then
            lunch twrp_${{ env.DEVICE_NAME }}-eng && make clean && mka adbd ${{ inputs.BUILD_TARGET }}image
        else
            lunch omni_${{ env.DEVICE_NAME }}-eng && make clean && mka ${{ inputs.BUILD_TARGET }}image
        fi

    - name: Set Build Date # For Build Date Info, currently using Asia/Manila
      run: |
        echo "BUILD_DATE=$(TZ=Asia/Manila date +%Y%m%d)" >> $GITHUB_ENV

    - name: Check if Recovery Exist
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
        if [ -f out/target/product/${{ env.DEVICE_NAME }}/OrangeFox*.img ]; then
            echo "CHECK_IMG_IS_OK=true" >> $GITHUB_ENV
            echo "MD5_IMG=$(md5sum out/target/product/${{ env.DEVICE_NAME }}/OrangeFox*.img | cut -d ' ' -f 1)" >> $GITHUB_ENV
        else
            echo "Recovery out directory is empty."
        fi
        if [ -f out/target/product/${{ env.DEVICE_NAME }}/OrangeFox*.zip ]; then
            echo "CHECK_ZIP_IS_OK=true" >> $GITHUB_ENV
            echo "MD5_ZIP=$(md5sum out/target/product/${{ env.DEVICE_NAME }}/OrangeFox*.zip | cut -d ' ' -f 1)" >> $GITHUB_ENV
        else
            echo "Recovery out directory is empty."
        fi

    - name: Upload to Release
      if: env.CHECK_IMG_IS_OK == 'true' && env.CHECK_ZIP_IS_OK == 'true'
      uses: softprops/action-gh-release@master
      with:
        files: |
          OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ env.DEVICE_NAME }}/OrangeFox*.img
          OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ env.DEVICE_NAME }}/OrangeFox*.img.tar
          OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ env.DEVICE_NAME }}/OrangeFox*.zip
          OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ env.DEVICE_NAME }}/ramdisk-recovery.*
        name: Unofficial OrangeFox for ${{ env.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
          Build: ${{ inputs.MANIFEST_BRANCH }}
          Device: [Device Tree/Branch](${{ inputs.DEVICE_TREE }}/tree/${{ inputs.DEVICE_TREE_BRANCH }})
          Commit: Most recent [commit](${{ inputs.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }}) during building.
          MD5 (img): ${{ env.MD5_IMG }}
          MD5 (zip): ${{ env.MD5_ZIP }}
          
    - name: Run LDCheck
      if: inputs.LDCHECK == 'true'
      run: |
        cd tools
        mv -n libneeds ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ env.DEVICE_NAME }}/recovery/root/
        mv -n ldcheck ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ env.DEVICE_NAME }}/recovery/root/
        cd ../OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ env.DEVICE_NAME }}/recovery/root
        python3 ldcheck -p system/lib64:vendor/lib64:system/lib:vendor/lib -d ${{ inputs.LDCHECKPATH }}
        echo "Done checking missing dependencies. Review, and reconfigure your tree."
      continue-on-error: true
