
name: PBRP Builder New

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'PBRP Manifest Branch'
        required: true
        default: 'android-9-0'
        type: choice
        options:
        - android-14.0
        - android-12.1
        - android-11.0
        - android-10.0
        - android-9.0
        - android-8.1
        - android-7.1
        - android-6.0
      DEVICE_TREE:
        description: 'Custom Recovery Tree URL'
        required: true
        default: 'https://github.com/vados-dev/sl8541e_cus_go'
      DEVICE_TREE_BRANCH:
        description: 'Device Tree Branch (optional)'
        required: false
        default: 'android-9.0'
      BUILD_TARGET:
        description: 'Build Target (use "pbrp" for Android 11+)'
        required: true
        default: 'pbrp'
        type: choice
        options:
        - pbrp
        - recovery
        - boot
        - vendorboot
      LDCHECK_PATH:
        description: 'Path for dependency check (optional)'
        required: false
        default: 'recovery/root/system/bin/qseecomd'

jobs:
  build:
    name: Build PBRP (new) by ${{ github.actor }}
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      GITHUB_TOKEN: ${{ secrets.amster }}
    permissions:
      contents: write

    steps:
    - name: Initial Setup
      run: |
        echo "BUILD_START=$(date +%s)" >> $GITHUB_ENV
        echo "BUILD_DATE=$(TZ=UTC date +%Y%m%d)" >> $GITHUB_ENV
        
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clean-up
      uses: rokibhasansagar/slimhub_actions@main

    - name: Swap Space   # Easier
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 24

    - name: Build PitchBlack Recovery
      uses: vados-dev/pitchblack-pbrp-builder-action@main
      id: build
      with:
        MANIFEST_BRANCH: ${{ inputs.MANIFEST_BRANCH }}
        DEVICE_TREE:  ${{ inputs.DEVICE_TREE }}
        DEVICE_TREE_BRANCH:  ${{ inputs.DEVICE_TREE_BRANCH }}
        BUILD_TARGET:  ${{ inputs.BUILD_TARGET }}
  
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      if: inputs.upload_releases == false || github.event_name != 'workflow_dispatch'
      with:
        name: PBRP-Recovery-${{ env.DEVICE_NAME }}-${{ env.BUILD_DATE }}
        path: |
          ${{ env.OUTPUT_DIR }}/*.img
          ${{ env.OUTPUT_DIR }}/*.tar
          ${{ env.OUTPUT_DIR }}/*vbmeta*
          ${{ env.OUTPUT_DIR }}/*.cpio

    - name: Upload to Release
      if: success()
      #uses: softprops/action-gh-release@v2
      uses: softprops/action-gh-release@master
      with:
        files: |
          android-recovery/out/target/product/${{ env.DEVICE_NAME }}/${{ env.BUILD_TARGET_NAME }}.img
          android-recovery/out/target/product/${{ env.DEVICE_NAME }}/PBRP*.zip
          android-recovery/out/target/product/${{ env.DEVICE_NAME }}/ramdisk-recovery.*
          #${{ env.OUTPUT_DIR }}/*.img
          #${{ env.OUTPUT_DIR }}/PBRP*.zip
          
        name: Unofficial PBRP for ${{ env.DEVICE_NAME }} - ${{ env.BUILD_DATE }}
        #name: PBRP for ${{ inputs.DEVICE_NAME }} - ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
          ## Build Information
          - **Build Date:** ${{ env.BUILD_DATE }}
          - **Build:** ${{ inputs.MANIFEST_BRANCH }}
          - **Build Type:** ${{ inputs.BUILD_TARGET }}
          - **Device:** [Device Tree/Branch](${{ inputs.DEVICE_TREE }}/tree/${{ inputs.DEVICE_TREE_BRANCH }})
          - **Commit:** Most recent [commit](${{ inputs.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }}) during building.
          #- **Branch:** ${{ inputs.MANIFEST_BRANCH }}
          #- **Device:** ${{ inputs.DEVICE_NAME }}
          
          ## Source Information
          - **Device Tree:** [${{ inputs.DEVICE_TREE }}](${{ inputs.DEVICE_TREE }}/tree/${{ inputs.DEVICE_TREE_BRANCH }})
          - **Branch:** ${{ inputs.DEVICE_TREE_BRANCH }}
          
          ## Build Status
          - Recovery Image MD5: `${{ env.MD5_IMG }}`
          - ZIP Package MD5: `${{ env.MD5_ZIP }}`
          
          > Note: This is an automated build. Please test thoroughly before using.
        prerelease: true
        draft: false

    - name: Run LDCHECK
      uses: vados-dev/ldcheck-action@main
      with:
        OUTPUT_DIR: ${{ env.OUTPUT_DIR }}
        LDCHECKPATH: ${{ inputs.LDCHECK_PATH }}
      continue-on-error: true

    - name: Calculate Build Time
      if: always()
      run: |
        BUILD_END=$(date +%s)
        BUILD_DURATION=$((BUILD_END - BUILD_START))
        
        hours=$((BUILD_DURATION / 3600))
        minutes=$(((BUILD_DURATION % 3600) / 60))
        seconds=$((BUILD_DURATION % 60))
        
        echo "Build completed in ${hours}h ${minutes}m ${seconds}s"
        
        # Save build statistics
        echo "BUILD_DURATION=${BUILD_DURATION}" >> $GITHUB_ENV
        echo "BUILD_HOURS=${hours}" >> $GITHUB_ENV
        echo "BUILD_MINUTES=${minutes}" >> $GITHUB_ENV
        echo "BUILD_SECONDS=${seconds}" >> $GITHUB_ENV

    - name: Cleanup Workspace
      if: always()
      run: |
        cd ${{ github.workspace }}
        rm -rf android-recovery
        df -h
